modLoader = "kotlinforforge"
loaderVersion = "[4.4,)"
license = "MIT"
issueTrackerURL="https://github.com/AyOhEe/create-track-map/issues"

[[mods]]
modId = "createtrackmap"
version = "${version}"
displayName = "Create Track Map"
displayURL="https://github.com/AyOhEe/create-track-map"
authors = "LittleChaSiu, AyOhEe"
description = "A map of Create train tracks"
logoFile = "assets/littlechasiu/ctm/static/assets/logo.png"

[[dependencies.createtrackmap]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createtrackmap]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.createtrackmap]]
modId = "create"
mandatory = true
versionRange = "[${create_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createtrackmap]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[${kff_version},)"
ordering = "AFTER"
side = "BOTH"
